//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  E:\Siemens\CustomFunction\application\SprayEffectEvalutatorDialog.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: 10609
//              Version: NX 2412
//              Date: 11-06-2025  (Format: mm-dd-yyyy)
//              Time: 21:08 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "SprayEffectEvalutatorDialog.hpp"
#include <NXOpen/NXObjectManager.hxx>
#include <uf_curve.h>
#include <uf_disp.h>
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(SprayEffectEvalutatorDialog::theSession) = NULL;
UI *(SprayEffectEvalutatorDialog::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
SprayEffectEvalutatorDialog::SprayEffectEvalutatorDialog()
    : m_evaluator(nullptr)  // === 新增：初始化evaluator指针 ===
{
    try
    {
        // Initialize the NX Open C++ API environment
        SprayEffectEvalutatorDialog::theSession = NXOpen::Session::GetSession();
        SprayEffectEvalutatorDialog::theUI = UI::GetUI();
        theDlxFileName = "SprayEffectEvalutatorDialog.dlx";
        theDialog = SprayEffectEvalutatorDialog::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &SprayEffectEvalutatorDialog::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &SprayEffectEvalutatorDialog::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &SprayEffectEvalutatorDialog::update_cb));
        theDialog->AddFilterHandler(make_callback(this, &SprayEffectEvalutatorDialog::filter_cb));
        theDialog->AddInitializeHandler(make_callback(this, &SprayEffectEvalutatorDialog::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &SprayEffectEvalutatorDialog::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
SprayEffectEvalutatorDialog::~SprayEffectEvalutatorDialog()
{
    // === 新增：释放evaluator资源 ===
    if (m_evaluator != nullptr) {
        delete m_evaluator;
        m_evaluator = nullptr;
    }

    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}


//------------------------------------------------------------------------------
//This method launches the dialog to screen
//------------------------------------------------------------------------------
NXOpen::BlockStyler::BlockDialog::DialogResponse SprayEffectEvalutatorDialog::Launch()
{
    NXOpen::BlockStyler::BlockDialog::DialogResponse dialogResponse= NXOpen::BlockStyler::BlockDialog::DialogResponse::DialogResponseInvalid;
    try
    {
        dialogResponse=theDialog->Launch();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SprayEffectEvalutatorDialog::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return dialogResponse;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void SprayEffectEvalutatorDialog::initialize_cb()
{
    try
    {
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        sheetregion_select = dynamic_cast<NXOpen::BlockStyler::BodyCollector*>(theDialog->TopBlock()->FindBlock("sheetregion_select"));
        group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group1"));
        splinecurve_select = dynamic_cast<NXOpen::BlockStyler::CurveCollector*>(theDialog->TopBlock()->FindBlock("splinecurve_select"));
        group2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group2"));
        evalutor_button = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("evalutor_button"));
        group3 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group3"));
        poorarea_list = dynamic_cast<NXOpen::BlockStyler::ListBox*>(theDialog->TopBlock()->FindBlock("poorarea_list"));
        curvepoint_sel = dynamic_cast<NXOpen::BlockStyler::SelectObject*>(theDialog->TopBlock()->FindBlock("curvepoint_sel"));
        createcurve_button = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("createcurve_button"));
        //------------------------------------------------------------------------------
        //Registration of ListBox specific callbacks
        //------------------------------------------------------------------------------
        //poorarea_list->SetAddHandler(make_callback(this, &SprayEffectEvalutatorDialog::AddCallback));
        
        //poorarea_list->SetDeleteHandler(make_callback(this, &SprayEffectEvalutatorDialog::DeleteCallback));
        
        //------------------------------------------------------------------------------
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SprayEffectEvalutatorDialog::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void SprayEffectEvalutatorDialog::dialogShown_cb()
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SprayEffectEvalutatorDialog::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int SprayEffectEvalutatorDialog::apply_cb()
{
    int errorCode = 0;
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        SprayEffectEvalutatorDialog::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int SprayEffectEvalutatorDialog::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == sheetregion_select)
        {
        //---------Enter your code here-----------
        }
        else if(block == splinecurve_select)
        {
        //---------Enter your code here-----------
        }
        else if(block == evalutor_button)
        {

            PropertyList* bodyProps = sheetregion_select->GetProperties();
            std::vector<TaggedObject*> selectedBodies = bodyProps->GetTaggedObjectVector("SelectedObjects");
            delete bodyProps;

            if (selectedBodies.empty()) {
                theUI->NXMessageBox()->Show("错误", NXMessageBox::DialogTypeError,
                                             "请先选择要评估的片体区域");
                return 0;
            }

            PropertyList* curveProps = splinecurve_select->GetProperties();
            std::vector<TaggedObject*> selectedCurves = curveProps->GetTaggedObjectVector("SelectedObjects");
            delete curveProps;

            if (selectedCurves.empty()) {
                theUI->NXMessageBox()->Show("错误", NXMessageBox::DialogTypeError,
                                             "请先选择喷涂路径曲线");
                return 0;
            }

           
            std::vector<tag_t> curveTags;
            for (TaggedObject* obj : selectedCurves) {
                curveTags.push_back(obj->Tag());
            }

           
            std::vector<NXOpen::Body*> regionBodies;
            for (TaggedObject* obj : selectedBodies) {
                NXOpen::Body* body = dynamic_cast<NXOpen::Body*>(obj);
                if (body != nullptr) {
                    regionBodies.push_back(body);
                }
            }

            
            if (m_evaluator != nullptr) {
                delete m_evaluator;
            }
            m_evaluator = new SprayEffectEvaluator(curveTags, regionBodies);

            
            bool success = m_evaluator->EvaluateAllRegions();

            if (!success) {
                theUI->NXMessageBox()->Show("错误", NXMessageBox::DialogTypeError,
                                             "评估失败，请检查输入数据");
                return 0;
            }

            m_currentBadAreas = m_evaluator->GetBadAreaClusters();

            PropertyList* listProps = poorarea_list->GetProperties();

            std::vector<NXString> emptyList;
            listProps->SetStrings("ListItems", emptyList);

            std::vector<NXString> badAreaItems;
            for (const BadAreaCluster& cluster : m_currentBadAreas) {
                std::ostringstream oss;
                oss << "badArea" << cluster.id;
                badAreaItems.push_back(NXString(oss.str().c_str()));
            }
            listProps->SetStrings("ListItems", badAreaItems);
            delete listProps;
        }
        else if(block == poorarea_list)
        {
            // === poorarea_list 选择回调实现 ===

            // 检查evaluator是否存在
            if (m_evaluator == nullptr) {
                return 0;
            }

            // 获取当前选中的项目
            PropertyList* listProps = poorarea_list->GetProperties();
            std::vector<int> selectedIndices = listProps->GetIntegerVector("SelectedItems");
            delete listProps;

            // 如果没有选中项，清除显示
            if (selectedIndices.empty()) {
                UF_DISP_refresh();  // 清除templine显示
                m_evaluator->ClearTempPoints();  // 清除临时点
                return 0;
            }

            // 获取第一个选中项的索引
            int selectedIndex = selectedIndices[0];

            // 验证索引有效性
            if (selectedIndex >= 0 && selectedIndex < m_currentBadAreas.size()) {
                // 绘制选中的badArea三角形（自动刷新显示，清除之前的templine）
                m_evaluator->DrawBadAreaTriangles(selectedIndex);

                // 为选中的badArea创建临时点（自动清除旧点）
                m_evaluator->CreatePointsForBadArea(selectedIndex);
            }
        }
        else if(block == curvepoint_sel)
        {
        //---------Enter your code here-----------
        }
        else if(block == createcurve_button)
        {
            // === 生成曲线按钮回调实现 ===

            // 1. 检查是否已选择badArea
            PropertyList* listProps = poorarea_list->GetProperties();
            std::vector<int> selectedIndices = listProps->GetIntegerVector("SelectedItems");
            delete listProps;

            if (selectedIndices.empty()) {
                theUI->NXMessageBox()->Show("提示", NXMessageBox::DialogTypeInformation,
                                             "请先在列表中选择一个badArea");
                return 0;
            }

            int selectedBadAreaIndex = selectedIndices[0];  // 取第一个选中项

            if (selectedBadAreaIndex >= m_currentBadAreas.size()) {
                theUI->NXMessageBox()->Show("错误", NXMessageBox::DialogTypeError,
                                             "选中的badArea索引无效");
                return 0;
            }

            // 2. 从curvepoint_sel中直接获取所有选中的点对象
            std::vector<NXOpen::TaggedObject*> selectedObjects = curvepoint_sel->GetSelectedObjects();

            if (selectedObjects.empty()) {
                theUI->NXMessageBox()->Show("提示", NXMessageBox::DialogTypeInformation,
                                             "请先选择点来创建补充路径曲线");
                return 0;
            }

            // 3. 提取所有选中点的坐标
            std::vector<Point3d> selectedPoints;

            for (NXOpen::TaggedObject* obj : selectedObjects) {
                NXOpen::Point* nxPoint = dynamic_cast<NXOpen::Point*>(obj);
                if (nxPoint != nullptr) {
                    Point3d coord = nxPoint->Coordinates();
                    selectedPoints.push_back(coord);
                }
            }

            // 检查有效点数量
            if (selectedPoints.size() < 2) {
                theUI->NXMessageBox()->Show("提示", NXMessageBox::DialogTypeInformation,
                                             "需要至少2个点才能生成曲线");
                return 0;
            }

            int numPoints = selectedPoints.size();
            tag_t curve_id = NULL_TAG;
            std::string curveType;

            // 4. 根据点数生成不同类型的曲线
            if (numPoints == 2) {
                // === 2个点：生成直线 ===
                curveType = "直线";

                double startPt[3] = { selectedPoints[0].X, selectedPoints[0].Y, selectedPoints[0].Z };
                double endPt[3] = { selectedPoints[1].X, selectedPoints[1].Y, selectedPoints[1].Z };
				UF_CURVE_line_t lineDef;
				UF_VEC3_copy(startPt, lineDef.start_point);
				UF_VEC3_copy(endPt, lineDef.end_point);
                

                int error = UF_CURVE_create_line(&lineDef, &curve_id);

                if (error != 0) {
                    theUI->NXMessageBox()->Show("错误", NXMessageBox::DialogTypeError,
                                                 "直线生成失败");
                    return 0;
                }
            }
            else {
                // === 3个点及以上：生成样条曲线 ===
                curveType = "样条曲线";

                double* pt = new double[numPoints * 3];

                for (int i = 0; i < numPoints; i++) {
                    pt[i*3]   = selectedPoints[i].X;
                    pt[i*3+1] = selectedPoints[i].Y;
                    pt[i*3+2] = selectedPoints[i].Z;
                }

                int error = PDCAPP_COM_create_spline_f_pt(
                    pt, numPoints,
                    0, nullptr,  // 无起始切矢
                    0, nullptr,  // 无结束切矢
                    &curve_id
                );

                delete[] pt;

                if (error != 0) {
                    theUI->NXMessageBox()->Show("错误", NXMessageBox::DialogTypeError,
                                                 "样条曲线生成失败");
                    return 0;
                }
            }

            // 5. 设置曲线属性（与RegionCurveBuilder保持一致，不含PathIndex）
            BadAreaCluster& selectedCluster = m_currentBadAreas[selectedBadAreaIndex];
            tag_t regionTag = selectedCluster.regionBodyTag;

            try {
                NXOpen::NXObject* curveObj = dynamic_cast<NXOpen::NXObject*>(NXObjectManager::Get(curve_id));

                if (curveObj != nullptr) {
                    // 1. 标记为喷涂路径
                    curveObj->SetAttribute("IsSprayPath", 1, NXOpen::Update::Option::OptionNow);

                    // 2. 记录所属区域的Body Tag
                    curveObj->SetAttribute("RegionTag", static_cast<int>(regionTag),
                                           NXOpen::Update::Option::OptionNow);

                    // 3. 记录区域类型（使用整数）
                    curveObj->SetAttribute("RegionType", static_cast<int>(selectedCluster.regionType),
                                           NXOpen::Update::Option::OptionNow);

                    // 4. 添加字符串属性，便于识别
                    std::string regionTypeName;
                    switch (selectedCluster.regionType) {
                    case FaceRegionType::HORIZONTAL:
                        regionTypeName = "Horizontal";
                        break;
                    case FaceRegionType::CONVEX:
                        regionTypeName = "Convex";
                        break;
                    case FaceRegionType::CONCAVE:
                        regionTypeName = "Concave";
                        break;
                    case FaceRegionType::SIDEWALL:
                        regionTypeName = "Sidewall";
                        break;
                    case FaceRegionType::UNSORTED:
                        regionTypeName = "Unsorted";
                        break;
                    default:
                        regionTypeName = "Unknown";
                        break;
                    }
                    curveObj->SetAttribute("RegionTypeName", regionTypeName.c_str(),
                                           NXOpen::Update::Option::OptionNow);

                    // 5. 记录步距（喷砂工艺参数）
                    if (m_evaluator) {
                        double stepDistance = m_evaluator->GetStepDistance();
                        curveObj->SetAttribute("StepDistance", stepDistance,
                                               NXOpen::Update::Option::OptionNow);
                    }

                    // 6. 记录其他喷砂参数（与RegionCurveBuilder保持一致）
                    if (m_evaluator) {
                        double sprayDiameter = m_evaluator->GetSprayDiameter();
                        curveObj->SetAttribute("SprayDiameter", sprayDiameter,
                                               NXOpen::Update::Option::OptionNow);

                        double overlapRatio = m_evaluator->GetOverlapRatio();
                        curveObj->SetAttribute("OverlapRatio", overlapRatio,
                                               NXOpen::Update::Option::OptionNow);
                    }
                }
            }
            catch (...) {
                // 属性设置失败不影响主流程
            }

            // 6. 重新计算badArea的intensity并重绘
            if (m_evaluator) {
                try {
                    m_evaluator->RecalculateAndDrawBadArea(selectedBadAreaIndex, curve_id);

                    // 重新同步badArea数据（因为三角形的intensity已更新）
                    m_currentBadAreas = m_evaluator->GetBadAreaClusters();
                }
                catch (...) {
                    // 重新计算失败不影响主流程
                }
            }

            // 7. 成功提示
            std::ostringstream oss;
            oss << "成功生成补充路径" << curveType << "！\n"
                << "使用了 " << numPoints << " 个点\n"
                << "对应 badArea" << selectedCluster.id;

            theUI->NXMessageBox()->Show("成功", NXMessageBox::DialogTypeInformation,
                                         oss.str().c_str());

            std::vector<TaggedObject*> zero(0);
            curvepoint_sel->SetSelectedObjects(zero);
            
        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SprayEffectEvalutatorDialog::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int SprayEffectEvalutatorDialog::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        SprayEffectEvalutatorDialog::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: filter_cb
//------------------------------------------------------------------------------
int SprayEffectEvalutatorDialog::filter_cb(NXOpen::BlockStyler::UIBlock* block, NXOpen::TaggedObject* selectObject)
{
    // 曲线选择器的过滤逻辑
    if (block == curvepoint_sel) {
        try {
            NXOpen::Point* nxPoint  = dynamic_cast<NXOpen::Point*>(selectObject);
            if (nxPoint != nullptr) {
                
                return UF_UI_SEL_ACCEPT;
            }
        }
        catch (...) {
            // 属性不存在或读取失败，拒绝选择
        }
        return UF_UI_SEL_REJECT;
    }

    if (block == splinecurve_select) {
        try {
            NXOpen::NXObject* nxObj = dynamic_cast<NXOpen::NXObject*>(selectObject);
            if (nxObj != nullptr) {
                // 检查曲线是否有 IsSprayPath 属性且值为 1
                int isSprayPath = nxObj->GetIntegerAttribute("IsSprayPath");
                if (isSprayPath == 1) {
                    return UF_UI_SEL_ACCEPT;
                }
            }
        }
        catch (...) {
            // 属性不存在或读取失败，拒绝选择
        }
        return UF_UI_SEL_REJECT;
    }

    return(UF_UI_SEL_ACCEPT);
}
//------------------------------------------------------------------------------
//ListBox specific callbacks
//------------------------------------------------------------------------------
//int SprayEffectEvalutatorDialog::AddCallback (NXOpen::BlockStyler::ListBox* list_box)
//{
//}

//int SprayEffectEvalutatorDialog::DeleteCallback(NXOpen::BlockStyler::ListBox* list_box)
//{
//}

//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* SprayEffectEvalutatorDialog::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}
